name: Deploy to Zeit

on:
  push:
    branches:
      - dev
      - feature/*
      - master
      - release/*

jobs:
  deploy:
    name: Deploy to Zeit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Now
        if: github.ref == 'refs/heads/dev'
        env:
          NOW_ORG_ID: team_WtAI5aOHuDxYRprOgqAOqdAS
          NOW_PROJECT_ID: QmXGZT7Mta1bgttLGhBLdzShPyWSauKi7f2x3DtN1A17ma
          NOW_TOKEN: ${{ secrets.ZEIT_TOKEN }}
        run:
          now -A now.river.dev.json -t $NOW_TOKEN

      - name: Now
        if: github.ref == 'refs/heads/master'
        env:
          NOW_ORG_ID: team_WtAI5aOHuDxYRprOgqAOqdAS
          NOW_PROJECT_ID: QmXGZT7Mta1bgttLGhBLdzShPyWSauKi7f2x3DtN1A17ma
          NOW_TOKEN: ${{ secrets.ZEIT_TOKEN }}
        run:
          now -A now.river.prod.json --prod -t $NOW_TOKEN
